feat : Add outcome on teams

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -9,6 +9,7 @@ variables:
   NODE_ENV: 'production'
   DOCKER_HOST: "tcp://docker:2375/"
   DOCKER_TLS_CERTDIR: ""
+  TEAMS_WEBHOOK_URL: "https://epitechfr.webhook.office.com/webhookb2/0847c46d-a93b-4c0b-a417-a1c4b63b47c0@901cb4ca-b862-4029-9306-e5cd0f6d9f86/IncomingWebhook/f569423dffab438cbebff4778201e9e2/4b235b50-7405-4659-9db9-ce370427f74f/V2kmSd8pAHLBLSJNpN8F9c6YNrLCnOXkvyiziU3ezVi0w1"
 
 # Utilisation des runners Docker
 default:
@@ -26,6 +27,8 @@ install_frontend:
     - echo "Installing frontend dependencies"
     - cd trinity
     - npm install
+    - echo "Forcing failure to test Teams notification"
+    - exit 1
     - echo "Frontend dependencies installed"
   artifacts:
     paths:
@@ -34,6 +37,13 @@ install_frontend:
     - feature/docker-configuration-siga
     - main
     - dev
+  after_script:
+    - |
+      if [ "$CI_JOB_STATUS" != "success" ]; then
+        curl -H "Content-Type: application/json" \
+        -d "{\"text\": \"🚨 Pipeline Failed on job: install_frontend for project $CI_PROJECT_NAME (branch: $CI_COMMIT_REF_NAME)\"}" \
+        $TEAMS_WEBHOOK_URL
+      fi
 
 # Étape d'installation des dépendances pour le backend
 install_backend:
@@ -50,6 +60,13 @@ install_backend:
     - feature/docker-configuration-siga
     - main
     - dev
+  after_script:
+    - |
+      if [ "$CI_JOB_STATUS" != "success" ]; then
+        curl -H "Content-Type: application/json" \
+        -d "{\"text\": \"🚨 Pipeline Failed on job: install_backend for project $CI_PROJECT_NAME (branch: $CI_COMMIT_REF_NAME)\"}" \
+        $TEAMS_WEBHOOK_URL
+      fi
 
 # Étape de build du frontend
 build_frontend:
@@ -66,6 +83,13 @@ build_frontend:
     - feature/docker-configuration-siga
     - main
     - dev
+  after_script:
+    - |
+      if [ "$CI_JOB_STATUS" != "success" ]; then
+        curl -H "Content-Type: application/json" \
+        -d "{\"text\": \"🚨 Pipeline Failed on job: build_frontend for project $CI_PROJECT_NAME (branch: $CI_COMMIT_REF_NAME)\"}" \
+        $TEAMS_WEBHOOK_URL
+      fi
 
 # Étape de tests pour le frontend
 test_frontend:
@@ -78,6 +102,13 @@ test_frontend:
   only:
     - main
     - dev
+  after_script:
+    - |
+      if [ "$CI_JOB_STATUS" != "success" ]; then
+        curl -H "Content-Type: application/json" \
+        -d "{\"text\": \"🚨 Pipeline Failed on job: test_frontend for project $CI_PROJECT_NAME (branch: $CI_COMMIT_REF_NAME)\"}" \
+        $TEAMS_WEBHOOK_URL
+      fi
 
 # Étape de tests pour le backend
 test_backend:
@@ -91,16 +122,13 @@ test_backend:
     - feature/docker-configuration-siga
     - main
     - dev
-
-# Étape de test simple pour vérifier le fonctionnement du runner
-test_runner:
-  stage: test
-  script:
-    - echo "Hello, GitLab Runner!"
-  only:
-    - feature/docker-configuration-siga
-    - main
-    - dev
+  after_script:
+    - |
+      if [ "$CI_JOB_STATUS" != "success" ]; then
+        curl -H "Content-Type: application/json" \
+        -d "{\"text\": \"🚨 Pipeline Failed on job: test_backend for project $CI_PROJECT_NAME (branch: $CI_COMMIT_REF_NAME)\"}" \
+        $TEAMS_WEBHOOK_URL
+      fi
 
 # Étape de déploiement pour l'environnement de développement
 deploy_dev:
@@ -111,6 +139,13 @@ deploy_dev:
   only:
     - feature/docker-configuration-siga
     - dev
+  after_script:
+    - |
+      if [ "$CI_JOB_STATUS" != "success" ]; then
+        curl -H "Content-Type: application/json" \
+        -d "{\"text\": \"🚨 Pipeline Failed on job: deploy_dev for project $CI_PROJECT_NAME (branch: $CI_COMMIT_REF_NAME)\"}" \
+        $TEAMS_WEBHOOK_URL
+      fi
 
 # Étape de déploiement pour l'environnement de production
 deploy_prod:
@@ -122,3 +157,10 @@ deploy_prod:
     - feature/docker-configuration-siga
     - main
   when: manual  # Optionnel, pour le déploiement manuel en production
+  after_script:
+    - |
+      if [ "$CI_JOB_STATUS" != "success" ]; then
+        curl -H "Content-Type: application/json" \
+        -d "{\"text\": \"🚨 Pipeline Failed on job: deploy_prod for project $CI_PROJECT_NAME (branch: $CI_COMMIT_REF_NAME)\"}" \
+        $TEAMS_WEBHOOK_URL
+      fi
